version: "2.1"
jobs:
  build:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - run: npx flip-table -o 'docker'
      - run: |
          ! [[ $CIRCLE_BRANCH == "gh-readonly-queue"* ]]
workflows:
  build:
    jobs:
      - build
