version: "2.1"
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install --user doge
      - run: doge
workflows:
  build:
    jobs:
      - build
