version: "2.1"
jobs:
  build:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - run: env
      - run: npx flip-table -o 'docker'
workflows:
  build:
    jobs:
      - build
